# Generated by Django 5.0.3 on 2024-04-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPractice', '0002_question_subject_alter_user_email_alter_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qus',
            new_name='question_text',
        ),
    ]
